micronaut:
  application:
    name: thoughtsporadic-be
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://blog.thoughtsporadic.com
      localhost-pass-through: true
netty:
  default:
    allocator:
      max-order: 3
