micronaut:
  application:
    name: thoughtsporadic-be
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - ^http(|s)://(www|blog)\.thoughtsporadic\.com$
          allowedMethods:
            - GET
            - POST
          exposedHeaders:
            - Content-Type
            - Cache-Control
            - Content-Language
            - Content-Length
            - Expires
            - Last-Modified
          allowedCredentials: false
      localhost-pass-through: true
netty:
  default:
    allocator:
      max-order: 3
